repos:
  - repo: local
    hooks:
      - id: format-check
        name: Check code formatting
        entry: uv run poe format-check
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: lint-check
        name: Check code linting
        entry: uv run poe lint-check
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: typecheck
        name: Type checking
        entry: uv run poe typecheck
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: test
        name: Unit tests
        entry: uv run poe test
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: commitizen-check
        name: Check commit message
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
